apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "helm.ingressRoute" . }}
spec:
  entryPoints:                      # [1]
  - web
  routes: {{- include "helm.routes" . | indent 4 }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "helm.ingressMiddleware.replaceWeb" . }}
spec:
  replacePathRegex:
    regex: ^/web(/|$)(.*)
    replacement: /$2

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "helm.ingressMiddleware.replaceGraphql" . }}
spec:
  replacePathRegex:
    regex: ^/graphql-router(/|$)(.*)
    replacement: /$2
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "helm.ingressMiddleware.replaceFile" . }}
spec:
  replacePathRegex:
    regex: ^/file(/|$)(.*)
    replacement: /$2
