apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "helm.ingress-route" . }}
spec:
  entryPoints:                      # [1]
    - web
  routes:                           # [2]
  - kind: Rule
    match: Host(`{{ .Values.hostname }}`) && PathPrefix(`/web`) # [3]
    priority: 30                    # [4]
    middlewares:
    - name: {{ include "helm.ingress-route" . }}-replace-web
    services:                       # [8]
    - kind: Service
      name: {{ include "helm.web-app" .}}
      passHostHeader: true
      port: 4000                      # [9]
  - kind: Rule
    match: Host(`{{ .Values.hostname }}`) && PathPrefix(`/graphql-router`) # [3]
    priority: 40                    # [4]
    middlewares:
    - name: {{ include "helm.ingress-route" . }}-replace-graphql-router
    services:                       # [8]
    - kind: Service
      name: {{ include "helm.server.graphql-router" .}}
      passHostHeader: true
      port: 4000                      # [9]
  - kind: Rule
    match: Host(`{{ .Values.hostname }}`) && PathPrefix(`/file`) # [3]
    priority: 40                    # [4]
    middlewares:
    - name: {{ include "helm.ingress-route" . }}-replace-file
    services:                       # [8]
    - kind: Service
      name: {{ include "helm.server.file" .}}
      passHostHeader: true
      port: 80                      # [9]
  - kind: Rule
    match: Host(`{{ .Values.hostname }}`) # [3]
    priority: 10                    # [4]
    services:                       # [8]
    - kind: Service
      name: {{ include "helm.web-app" .}}
      passHostHeader: true
      port: 4000                      # [9]
  # ngrok
  - kind: Rule
    match: HostRegexp(`{subdomain:.+?}.ngrok.io`) && PathPrefix(`/graphql-router`) # [3]
    priority: 20                    # [4]
    middlewares:
    - name: {{ include "helm.ingress-route" . }}-replace-graphql-router
    services:                       # [8]
    - kind: Service
      name: {{ include "helm.server.graphql-router" .}}
      passHostHeader: true
      port: 4000                      # [9]
  - kind: Rule
    match: HostRegexp(`{subdomain:.+?}.ngrok.io`) && PathPrefix(`/file`) # [3]
    priority: 20                    # [4]
    middlewares:
    - name: {{ include "helm.ingress-route" . }}-replace-file
    services:                       # [8]
    - kind: Service
      name: {{ include "helm.server.file" .}}
      passHostHeader: true
      port: 80                      # [9]
  - kind: Rule
    match: HostRegexp(`{subdomain:.+?}.ngrok.io`) # [3]
    priority: 10                    # [4]
    services:                       # [8]
    - kind: Service
      name: {{ include "helm.web-app" .}}
      passHostHeader: true
      port: 4000                      # [9]

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "helm.ingress-route" . }}-replace-web
spec:
  replacePathRegex:
    regex: ^/web(/|$)(.*)
    replacement: /$2

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "helm.ingress-route" . }}-replace-graphql-router
spec:
  replacePathRegex:
    regex: ^/graphql-router(/|$)(.*)
    replacement: /$2
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "helm.ingress-route" . }}-replace-file
spec:
  replacePathRegex:
    regex: ^/file(/|$)(.*)
    replacement: /$2
