apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.server.location" . }}
  labels:
    app: {{ include "helm.server.location" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "helm.server.location" . }}
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "helm.server.location" . }}
    spec:
      imagePullSecrets:
        - name: dpr-secret
      containers:
        - name: {{ include "helm.server.location" . }}
          image: ghcr.io/ndthanhdev/x2258-server-location:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.serverLocation }}
                  key: DB_HOST
                  optional: false
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.serverLocation }}
                  key: DB_PORT
                  optional: false
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.serverLocation }}
                  key: DB_USER
                  optional: false
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.serverLocation }}
                  key: DB_PASSWORD
                  optional: false
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.serverLocation }}
                  key: DB_NAME
                  optional: false
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.server.location" . }}
  namespace: default
spec:
  selector:
    app: {{ include "helm.server.location" . }}
  type: LoadBalancer
  ports:
    - name: {{ include "helm.server.location" . }}
      protocol: TCP
      port: 80
      targetPort: 4000
