apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.server.file" .}}
data:
  # property-like keys; each key maps to a simple value
  SEAWEEDFS_MASTER: {{ .Values.seaweedfs.master }}
  SEAWEEDFS_VOLUME: {{ .Values.seaweedfs.volume }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.server.file" . }}
  labels:
    app: {{ include "helm.server.file" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "helm.server.file" . }}
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "helm.server.file" . }}
    spec:
      imagePullSecrets:
        - name: dpr-secret
      containers:
        - name: {{ include "helm.server.file" . }}
          image: ghcr.io/ebox-org/ebox-server-file:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: SEAWEEDFS_MASTER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "helm.server.file" . }}
                  key: SEAWEEDFS_MASTER
                  optional: false
            - name: SEAWEEDFS_VOLUME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "helm.server.file" . }}
                  key: SEAWEEDFS_VOLUME
                  optional: false
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.server.file" . }}
  namespace: default
spec:
  selector:
    app: {{ include "helm.server.file" . }}
  type: LoadBalancer
  ports:
    - name: {{ include "helm.server.file" . }}
      protocol: TCP
      port: 80
      targetPort: 4000
