// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	MessageID   string `json:"messageID"`
	FromID      string `json:"fromID"`
	ToID        string `json:"toID"`
	MessageType string `json:"messageType"`
	Content     string `json:"content"`
}

func (Message) IsEntity() {}

type MessageInput struct {
	FromID      string `json:"fromID"`
	ToID        string `json:"toID"`
	MessageType string `json:"messageType"`
	Content     string `json:"content"`
}
