// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LocationInput struct {
	NodeID    string  `json:"nodeID"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type Nearby struct {
	Node     *Node   `json:"node"`
	Distance float64 `json:"distance"`
}

type Node struct {
	NodeID string `json:"nodeID"`
}

func (Node) IsEntity() {}
