name: CI

on:
  - push

env:
  VAR: dagger

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Dagger
        uses: dagger/dagger-for-github@v3
        with:
          install-only: true

      - name: Show Dagger version
        run: dagger version

      - name: Update
        run: dagger do release -l=debug
        working-directory: misc/pipes

      - name: Release
        run: dagger project update
        working-directory: misc/pipes
        env:
          REGISTRY_USERNAME: ${{ secrets.MACHINE_USER }}
          REGISTRY_PASSWORD: ${{ secrets.MACHINE_TOKEN }}
