name: CI

on:
  - push

env:
  VAR: dagger

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: |
            linux/amd64
            linux/arm64

      - name: Dagger
        uses: dagger/dagger-for-github@v3
        with:
          workdir: misc/pipes
          cmds: |
            project update
            version
            do release -l=debug
        env:
          REGISTRY_USERNAME: ${{ secrets.MACHINE_USER }}
          REGISTRY_PASSWORD: ${{ secrets.MACHINE_TOKEN }}
